[build]
  command = "npx convex deploy --cmd 'npm run build'"
  publish = ".tanstack/start/build/client-dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Environment variables needed in Netlify UI (Site settings > Environment variables):
# 
# Required for client-side:
# - VITE_CONVEX_URL (from your Convex dashboard)
# - VITE_CLERK_PUBLISHABLE_KEY (from Clerk dashboard)
#
# Required for server-side:
# - CLERK_SECRET_KEY (from Clerk dashboard - for server-side auth)
# - CLERK_FRONTEND_API_URL (from Clerk dashboard - for Convex auth integration)
# - CLERK_WEBHOOK_SECRET (from Clerk dashboard - for webhook validation)

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# TanStack Start with Netlify target handles routing automatically
