/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppChannelIndexRouteImport } from './routes/_app.channel/index'
import { Route as AppDmDmIdRouteImport } from './routes/_app.dm/$dmId'
import { Route as AppChannelChannelIdRouteImport } from './routes/_app.channel/$channelId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelIndexRoute = AppChannelIndexRouteImport.update({
  id: '/channel/',
  path: '/channel/',
  getParentRoute: () => AppRoute,
} as any)
const AppDmDmIdRoute = AppDmDmIdRouteImport.update({
  id: '/dm/$dmId',
  path: '/dm/$dmId',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelChannelIdRoute = AppChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AppAccountRoute
  '/help': typeof AppHelpRoute
  '/home': typeof AppHomeRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/channel/$channelId': typeof AppChannelChannelIdRoute
  '/dm/$dmId': typeof AppDmDmIdRoute
  '/channel': typeof AppChannelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AppAccountRoute
  '/help': typeof AppHelpRoute
  '/home': typeof AppHomeRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/channel/$channelId': typeof AppChannelChannelIdRoute
  '/dm/$dmId': typeof AppDmDmIdRoute
  '/channel': typeof AppChannelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_app/channel/$channelId': typeof AppChannelChannelIdRoute
  '/_app/dm/$dmId': typeof AppDmDmIdRoute
  '/_app/channel/': typeof AppChannelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/help'
    | '/home'
    | '/search'
    | '/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/channel/$channelId'
    | '/dm/$dmId'
    | '/channel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/help'
    | '/home'
    | '/search'
    | '/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/channel/$channelId'
    | '/dm/$dmId'
    | '/channel'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/account'
    | '/_app/help'
    | '/_app/home'
    | '/_app/search'
    | '/_app/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_app/channel/$channelId'
    | '/_app/dm/$dmId'
    | '/_app/channel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channel/': {
      id: '/_app/channel/'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof AppChannelIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dm/$dmId': {
      id: '/_app/dm/$dmId'
      path: '/dm/$dmId'
      fullPath: '/dm/$dmId'
      preLoaderRoute: typeof AppDmDmIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channel/$channelId': {
      id: '/_app/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof AppChannelChannelIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHomeRoute: typeof AppHomeRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppChannelChannelIdRoute: typeof AppChannelChannelIdRoute
  AppDmDmIdRoute: typeof AppDmDmIdRoute
  AppChannelIndexRoute: typeof AppChannelIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppHelpRoute: AppHelpRoute,
  AppHomeRoute: AppHomeRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppChannelChannelIdRoute: AppChannelChannelIdRoute,
  AppDmDmIdRoute: AppDmDmIdRoute,
  AppChannelIndexRoute: AppChannelIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
